---
environment_tier: staging
default_region: us-west-2
region: "{% if override_region != '' %}{{ override_region }}{% else %}{{ default_region }}{% endif %}"
dns_points_to_load_balancer: "{{ load_balancers_enabled | bool }}"
use_spot_instances_for_roles:
  - aggregator
  - application
  - applicationapi
  - applicationq
  - build
  - inbound
  - logs
  - management
  - metrics
  - outbound
  - preview
