--- 
environment_tier: staging
default_region: us-west-2
region: "{% if override_region != '' %}{{ override_region }}{% else %}{{ default_region }}{% endif %}"
dns_points_to_load_balancer: "{{ load_balancers_enabled | bool }}"
default_ec2_ami_id: "ami-69912409"
ec2_ami_id: "{% if override_ec2_ami_id != '' %}{{ override_ec2_ami_id }}{% else %}{{ default_ec2_ami_id }}{% endif %}"
